== ri-visualization image:https://img.shields.io/badge/License-EPL%202.0-blue.svg["EPL 2.0", link="https://www.eclipse.org/legal/epl-2.0/"]
This component was created as a result of the OpenReq project funded by the European Union Horizon 2020 Research and Innovation programme under grant agreement No 732463.

== Technical description
=== What does the microservice do
The ri-visualization microservice is the web-based dashboard for analysing tweets.

[red]#Please be aware that this ms collects user interaction data. To turn it off, please consider removing line 9 in /public/index.html (<script src="https://api.openreq.eu/ri-logging/frontend/script"></script>)#


=== Which technologies are used
- Docker (-> https://www.docker.com/)
- vuejs (-> https://github.com/vuejs)
- echarts (-> https://echartsjs.com)
- vuetify (-> https://github.com/vuetifyjs/vuetify)


=== How to install it
This ms requires a running instance of link:https://github.com/OpenReqEU/ri-storage-twitter[ri-storage-twitter].

Run the following commands to start the microservice:

. docker build --build-arg "VUE_APP_BASE_URL=<URL_TO_ri-storage-twitter>" --build-arg "VUE_APP_BACKUP_URL=<URL_TO_OPTIONAL_BACKUP_BACKEND>" -t ri-visualization .

. docker run --rm -d -p 9707:9707 ri-visualization

== How to use it (high-level description)
No Swagger documentation as this component does not have api calls.

=== Notes for developers 
If you are interested in using this service it is important to note, that this dashboard uses three micro services of OpenReq, namely:

- link:https://github.com/OpenReqEU/ri-orchestration-twitter[ri-orchestration-twitter]

- link:https://github.com/OpenReqEU/ri-storage-twitter[ri-storage-twitter]

- link:https://github.com/OpenReqEU/ri-collection-explicit-feedback-twitter[ri-collection-explicit-feedback-twitter]

All of OpenReq's micro services share a single domain, which is defined in the `VUE_APP_BASE_URL`. You can either update this, or remove it from the build configuration and instead add your custom endoints in `src/RESTconf.js`.

=== Sources
None.

== How to contribute
See OpenReq project contribution link:https://github.com/OpenReqEU/OpenReq/blob/master/CONTRIBUTING.md[Guidlines]

== License
Free use of this software is granted under the terms of the EPL version 2 (EPL2.0).